# Generated by Django 5.2.5 on 2025-08-19 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_post_count_profile_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
