# Generated by Django 5.2.5 on 2025-08-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_post_options_post_author_post_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
